name: 友链申请
description: 申请添加友情链接（请确保您已在本站放置本站链接）
title: "[友链申请] "
labels: ["友链申请"]
body:
  - type: input
    id: name
    attributes:
      label: 站点名称
      placeholder: 如：woodfish
    validations:
      required: true

  - type: input
    id: homepage
    attributes:
      label: 站点主页
      description: 您的博客或网站首页 URL
      placeholder: https://example.com
    validations:
      required: true

  - type: input
    id: friend_page
    attributes:
      label: 友链页面
      description: 您网站上放置了本站链接的具体页面 URL（用于反链检测）
      placeholder: https://example.com/friends/
    validations:
      required: true

  - type: input
    id: avatar
    attributes:
      label: 头像链接（可选）
      description: 建议使用正方形图片，留空则使用默认头像
      placeholder: https://jinzhenyi.dpdns.org/assets/images/tx.png

  - type: input
    id: desc
    attributes:
      label: 一句话描述（可选）
      placeholder: 

  - type: checkboxes
    id: check
    attributes:
      label: 确认事项
      options:
        - label: 我已将jinzhenyi.dpdns.org链接添加至我的友链页面
          required: true